#ifndef     KEYPRESSSURFACES_HH_
# define    KEYPRESSSURFACES_HH_
enum KeyPressSurfaces
{
    KEY_PRESS_SURFACE_DEFAULT,
    KEY_PRESS_SURFACE_UP,
    KEY_PRESS_SURFACE_DOWN,
    KEY_PRESS_SURFACE_LEFT,
    KEY_PRESS_SURFACE_RIGHT,
    KEY_PRESS_SURFACE_TOTAL
};
#endif /* KEYPRESSSURFACES_HH_ */
